config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, path: 'auth', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, except: [:new, :create] do
    get 'lock', to: 'users#lock'
    get 'unlock', to: 'users#unlock'
  end

  resources :organizations do
    resources :organization_services, only: [:new, :create, :destroy]
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :services, except: :show

  resources :organization_services do
    resources :time_slots
    resources :workers, except: [:index, :show]

    resources :reservations, only: [:new, :create]
    post '/reservations/available_time', to: 'reservations#available_time'
  end

  resources :reservations, only: [:destroy]

  get '/search', to: 'search#index'
  get '/search/autocomplete', to: 'search#autocomplete'

  get 'home/index'
  root to: 'home#index'
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text             default(""), not null
#
class Service < ApplicationRecord
  has_many :organization_services, dependent: :restrict_with_error
  has_many :organizations, through: :organization_services

  searchkick searchable: [:name], word_start: [:name]
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to services_path
    else
      render :new
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])

    if @service.update(service_params)
      redirect_to services_path
    else
      render :edit
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    redirect_to services_path
  end

  private

  def service_params
    params.require(:service).permit(:name, :description)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/edit.html.erb
<h1>Edit "<%= @service.name %>"</h1>

<%= form_with model: @service do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: 'true' %>
  </div>

  <div class="field">
    <%= f.label :desciption %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/services/index.html.erb
<h1>Services</h1>

<%= link_to 'create service', new_service_path %>

<% unless @services.empty? %>
  <table>
    <thead>
      <tr>
        <th>id</th>
        <th>name</th>
        <th>created at</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @services.each do |service| %>
        <tr>
          <td><%= service.id %></td>
          <td><%= service.name %></td>
          <td><%= service.created_at %></td>
          <td><%= link_to "Edit", edit_service_path(service) %></td>
          <td><%= link_to "Destroy", service, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <tr>Currently there are no services</tr>
<% end %>

app/views/services/new.html.erb
<h1>Create new service</h1>

<%= form_with model: @service do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: 'true' %>
  </div>

  <div class="field">
    <%= f.label :desciption %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>