config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, path: 'auth', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, except: [:new, :create] do
    get 'lock', to: 'users#lock'
    get 'unlock', to: 'users#unlock'
  end

  resources :organizations do
    resources :organization_services, only: [:new, :create, :destroy]
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :services, except: :show

  resources :organization_services do
    resources :time_slots
    resources :workers, except: [:index, :show]

    resources :reservations, only: [:new, :create]
    post '/reservations/available_time', to: 'reservations#available_time'
  end

  resources :reservations, only: [:destroy]

  get '/search', to: 'search#index'
  get '/search/autocomplete', to: 'search#autocomplete'

  get 'home/index'
  root to: 'home#index'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @query = params[:search_query]
    redirect_to root_path if @query.nil? || @query.empty?

    @organizations_by_name,
    @organizations_by_services_hash = elasticsearch_available? ? search_elasticsearch(@query) : search_db(@query)

    return unless elasticsearch_available? && @organizations_by_name.empty? && @organizations_by_services_hash.empty?

    @organizations_by_name, @organizations_by_services_hash = search_db(@query)
  end

  def autocomplete
    @autocomplete_results = Organization.search(
      params[:query],
      fields: ['name'],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: { below: 5 }
    ).map(&:name) | Service.search(
      params[:query],
      fields: ['name'],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: { below: 5 }
    ).map(&:name)

    render json: @autocomplete_results
  end

  private

  def elasticsearch_available?
    response = Faraday.get 'http://localhost:9200'
    response.status == 200
  rescue Faraday::ConnectionFailed
    false
  end

  def search_elasticsearch(query)
    organizations_by_name = Organization.search(
      query,
      fields: ['name']
    ).to_a
    services = Service.search(
      query,
      fields: [:name]
    ).to_a

    process_search_results(organizations_by_name, services)
  end

  def search_db(query)
    organizations_by_name = Organization.where('name like ?', "%#{query}%").to_a
    services = Service.where('name like ?', "%#{query}%").to_a

    process_search_results(organizations_by_name, services)
  end

  def process_search_results(organizations_by_name, services)
    services.delete_if { |service| service.organizations.empty? }

    organizations_by_services = services.map(&:organizations).flatten.uniq
    organizations_by_name -= organizations_by_name & organizations_by_services

    organizations_by_services_hash = {}
    organizations_by_services.each do |organization|
      organizations_by_services_hash[organization] = []
      services.each do |service|
        organization.services.include?(service) && organizations_by_services_hash[organization] << service
      end
    end

    [organizations_by_name, organizations_by_services_hash]
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<h4>Search results for '<%= @query %>':</h4>

<% if @organizations_by_name %>
  <% @organizations_by_name.each do |organization| %>
    <div>
      <h5><%= link_to organization.name, organization_path(organization.id) %></h5>
    </div>
  <% end %>
<% end %>

<% if @organizations_by_services_hash %>
  <% @organizations_by_services_hash.keys.each do |organization| %>
    <div>
        <h5><%= link_to organization.name, organization_path(organization.id) %></h5>
        <% @organizations_by_services_hash[organization].each do |service| %>
          <li style="padding-left: 10px;">
            <% organization_service = organization.organization_services.find_by(service_id: service.id) %>
            <%= link_to service.name, new_organization_service_reservation_path(organization_service) %>
          </li>
        <% end %>
    </div>
  <% end %>
<% end %>