config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, path: 'auth', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, except: [:new, :create] do
    get 'lock', to: 'users#lock'
    get 'unlock', to: 'users#unlock'
  end

  resources :organizations do
    resources :organization_services, only: [:new, :create, :destroy]
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :services, except: :show

  resources :organization_services do
    resources :time_slots
    resources :workers, except: [:index, :show]

    resources :reservations, only: [:new, :create]
    post '/reservations/available_time', to: 'reservations#available_time'
  end

  resources :reservations, only: [:destroy]

  get '/search', to: 'search#index'
  get '/search/autocomplete', to: 'search#autocomplete'

  get 'home/index'
  root to: 'home#index'
end

app/models/time_slot.rb
# == Schema Information
#
# Table name: time_slots
#
#  id                      :bigint           not null, primary key
#  organization_service_id :bigint           not null
#  status                  :integer          default("vacant"), not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  start_time              :datetime         not null
#  end_time                :datetime         not null
#
class TimeSlot < ApplicationRecord
  belongs_to :organization_service
  has_one :reservation,    dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  enum status: {
    vacant: 0,
    booked: 1
  }
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :find_organization_service

  def index
    @time_slots = @organization_service.time_slots
  end

  def new
    @time_slot = @organization_service.time_slots.build
  end

  def create
    start_time = get_datetime('start')
    end_time = get_datetime('end')

    duration = time_slot_params[:time_slot_duration].to_i

    @time_slot = TimeSlot.new

    if duration.zero? || duration.nil?
      render :new
      return
    end

    time_slots_params_array = []

    current_day_start_time = start_time

    until current_day_start_time > end_time
      time = current_day_start_time

      until (time + duration.minutes).to_s(:time) > end_time.to_s(:time) || (time + duration.minutes).day != time.day
        time_slot_start_time = time
        time += duration.minutes
        time_slot_end_time = time

        unless overlaps?(TimeSlot.new(start_time: time_slot_start_time, end_time: time_slot_end_time))
          time_slots_params_array << {
            organization_service_id: @organization_service.id,
            start_time: time_slot_start_time,
            end_time: time_slot_end_time,
            status: :vacant
          }
        end
      end

      current_day_start_time += 1.day
    end

    begin
      TimeSlot.transaction do
        @time_slots = TimeSlot.create!(time_slots_params_array)
      end
    rescue ActiveRecord::RecordInvalid # => e
      render :new
    else
      redirect_to edit_organization_path(@organization_service.organization_id)
    end
  end

  def edit
    @time_slot = @organization_service.time_slots.find(params[:id])
  end

  def update
    @time_slot = @organization_service.time_slots.find(params[:id])

    start_time = get_datetime('start')
    end_time = get_datetime('end')

    updated_time_slot = TimeSlot.new(start_time: start_time, end_time: end_time)

    if !overlaps?(updated_time_slot, @time_slot.id)
      if @time_slot.update(start_time: start_time, end_time: end_time)
        redirect_to organization_service_time_slots_path(@organization_service)
      else
        render :edit
      end
    else
      render :edit  # можно выводить сообщение вроде "выбранный интервал времени пересекается с уже существующим"
    end
  end

  def destroy
    @time_slot = TimeSlot.find(params[:id])
    @time_slot.destroy

    redirect_to organization_service_time_slots_path(@organization_service)
  end

  private

  def time_slot_params
    params.require(:time_slot).permit(
      :start_date,
      :start_time,
      :end_date,
      :end_time,
      :time_slot_duration,
      :status
    )
  end

  def find_organization_service
    @organization_service = OrganizationService.find(params[:organization_service_id])
  end

  def get_datetime(time)
    DateTime.parse(
      "#{time_slot_params["#{time}_date"]} #{time_slot_params["#{time}_time"]}"
    )
  end

  def overlaps?(time_slot, currently_edited_time_slot_id = nil)
    overlappings = @organization_service.time_slots.where(
      '
      (end_time > ? and ? > end_time) or
      (start_time > ? and start_time < ?) or
      (start_time <= ? and end_time >= ?)
      ',
      time_slot.start_time, time_slot.end_time,
      time_slot.start_time, time_slot.end_time,
      time_slot.start_time, time_slot.end_time
    ).where.not(id: currently_edited_time_slot_id)

    !overlappings.empty?
  end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/edit.html.erb
<h2>edit time slot</h2>


<%= form_with model: [@organization_service, @time_slot] do |f| %>
    <div>
      <%= f.label :choose_date %><br />
      <%= f.text_field :start_date, class: 'datepicker', id: 'from-date' %>
    </div>

    <div>
      <%= f.label :choose_start_time %><br />
      <%= f.text_field :start_time, class: 'timepicker', id: 'from-time' %>
    </div>

    <div style="display: none;">
      <%= f.label :choose_end_date %><br />
      <%= f.text_field :end_date, class: 'datepicker', id: 'to-date' %>
    </div>

    <div>
      <%= f.label :choose_end_time %><br />
      <%= f.text_field :end_time, class: 'timepicker', id: 'to-time' %>
    </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<%= javascript_pack_tag 'time_slots' %>

app/views/time_slots/index.html.erb
<h1>Organization service <%= @organization_service.id %> time slots</h1>

<% @time_slots.each do |time_slot| %>
  <div>
    id: <%= time_slot.id %>
    <ul>
      <li><%= time_slot.start_time%></li>
      <li><%= time_slot.end_time%></li>
        <%= link_to 'edit', edit_organization_service_time_slot_path(@organization_service, time_slot) %> 
        <%= link_to "delete", organization_service_time_slot_path(@organization_service, time_slot), method: :delete, data: { confirm: "Are you sure?" }  %>
    </ul>
  </div>
<% end %>

<%= link_to 'add', new_organization_service_time_slot_path(@organization_service.id) %> 

app/views/time_slots/new.html.erb
<h1>New time slots</h1>

<%= form_with model: [@organization_service, @time_slot] do |f| %>
  <div>
    <div>
      <%= f.label :choose_start_date %><br />
      <%= f.text_field :start_date, class: 'datepicker', id: 'from-date' %>
    </div>

    <div>
      <%= f.label :choose_start_time %><br />
      <%= f.text_field :start_time, class: 'timepicker', id: 'from-time' %>
    </div>
  </div>

  <div>
    <div>
      <%= f.label :choose_end_date %><br />
      <%= f.text_field :end_date, class: 'datepicker', id: 'to-date' %>
    </div>

    <div>
      <%= f.label :choose_end_time %><br />
      <%= f.text_field :end_time, class: 'timepicker', id: 'to-time' %>
    </div>
  </div>

  <div class="field">
    <%= f.label 'time slot duration (minutes)' %><br />
    <%= f.number_field :time_slot_duration , min: 5, max: 240, step: 5, value: 30 %>
  </div>

  <div class="actions">
    <%= f.submit "Create", id: 'submit' %>
  </div>
<% end %>

<%= javascript_pack_tag 'time_slots' %>