config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users, path: 'auth', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users, except: [:new, :create] do
    get 'lock', to: 'users#lock'
    get 'unlock', to: 'users#unlock'
  end

  resources :organizations do
    resources :organization_services, only: [:new, :create, :destroy]
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments do
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :services, except: :show

  resources :organization_services do
    resources :time_slots
    resources :workers, except: [:index, :show]

    resources :reservations, only: [:new, :create]
    post '/reservations/available_time', to: 'reservations#available_time'
  end

  resources :reservations, only: [:destroy]

  get '/search', to: 'search#index'
  get '/search/autocomplete', to: 'search#autocomplete'

  get 'home/index'
  root to: 'home#index'
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  user_id     :bigint           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text             default(""), not null
#
class Organization < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :description, presence: true
  validates :user_id, presence: true

  belongs_to :user, -> { where role: :owner }

  has_many :organization_services, dependent: :destroy
  has_many :services, through: :organization_services
  has_many :comments, as: :commentable

  searchkick searchable: [:name], word_start: [:name]
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)

    begin
      if @organization.save
        redirect_to @organization
      else
        render :new
      end
    rescue ActiveRecord::RecordNotUnique
      render :new
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])

    begin
      if @organization.update(organization_params)
        redirect_to @organization
      else
        render :edit
      end
    rescue ActiveRecord::RecordNotUnique
      render :edit
    end
  end

  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy

    redirect_to organizations_path
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :description, :user_id)
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/edit.html.erb
<h1>Edit "<%= @organization.name %>"</h1>

<%= form_with model: @organization do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: 'true' %>
  </div>

  <div class="field">
    <%= f.label :desciption %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :owner_id %><br />
    <%= f.text_field :user_id %>
  </div>

  <% unless @organization.services.empty? %>
    <p>Services:</d>
    <% @organization.organization_services.each do |organization_service| %>
      <div>
        <%= organization_service.service.name %>
        <%= organization_service.service.description %>
        <%= link_to 'edit service', edit_service_path(organization_service.service) %>
        <%= link_to 'add time slots', new_organization_service_time_slot_path(organization_service) %>
        <%= link_to 'delete', organization_organization_service_path(@organization, organization_service), method: :delete, data: { confirm: "Are you sure?" } %>

        <div style="padding: 10px;">
          <p>Service workers:</p>
          <% organization_service.workers.each do |worker| %>
            <div>
              <%= "#{worker.last_name} #{worker.first_name}: #{worker.qualification}" %>
              <%= link_to 'edit', edit_organization_service_worker_path(organization_service, worker) %>
              <%= link_to 'delete', organization_service_worker_path(organization_service, worker), method: :delete, data: { confirm: "Are you sure?" }  %>
            </div>
          <% end %>
          <%= link_to 'add worker', new_organization_service_worker_path(organization_service) %>
        </div>
        
      </div>
    <% end %>
  <% end %>
  <%= link_to 'add service', new_organization_organization_service_path(@organization) %>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<%= link_to 'create organization', new_organization_path %>

<% unless @organizations.empty? %>
  <table>
    <thead>
      <tr>
        <th>id</th>
        <th>owner id</th>
        <th>name</th>
        <th>created at</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @organizations.each do |org| %>
        <tr>
          <td><%= org.id %></td>
          <td><%= org.user_id %></td>
          <td><%= org.name %></td>
          <td><%= org.created_at %></td>
          <td><%= link_to "Show", org %></td>
          <td><%= link_to "Edit", edit_organization_path(org) %></td>
          <td><%= link_to "Destroy", org, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <tr>Currently there are no organizations</tr>
<% end %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= form_with model: @organization do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: 'true' %>
  </div>

  <div class="field">
    <%= f.label :desciption %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :owner_id %><br />
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/organizations/show.html.erb
<h1><%= @organization.name %></h1>

<div id="org-description"><%= @organization.description %></div>

<% unless @organization.organization_services.empty? %>
  <p>Доступные услуги:</d>
  <% @organization.organization_services.each do |org_service| %>
    <div style="padding-left: 10px;">
      <%= org_service.service.name %>
      <%= link_to 'забронировать время', new_organization_service_reservation_path(org_service) %>
      <% unless org_service.workers.empty? %>
        <div style="padding: 10px;">
          <p >Staff:</p>
          <ul>
            <% org_service.workers.each do |worker| %>
              <li><%= "#{worker.last_name} #{worker.first_name} - #{worker.qualification}" %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>На данный момент нет доступных услуг</p>
<% end %>


<div id="comments-section">
  <div id="header">
    <h5>Comments</h5>

    <%= form_with(model: [@organization, Comment.new], id: 'new-comment-form', local: false) do |f| %>
      <%= f.text_area :content %><br/> 
      <%= f.submit 'add comment' %>
    <% end %>
  </div>

  <div id="comments">
    <%= render partial: 'comments/comment', collection: @organization.comments.order(id: :asc) %>
  </div>
</div>